@host=localhost:80
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJVc2VyIiwiZ2l2ZW5fbmFtZSI6IlVzZXIiLCJmYW1pbHlfbmFtZSI6IlVzZXIiLCJqdGkiOiIxMzk5NGM3My01ZTkzLTQyZGUtODA0ZC0yMDYzYzA3N2ZhM2IiLCJleHAiOjIwNDE2MzgzNzUsImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.BXl1O9uGSJAfdV6vpT9b2kwZqchHjEQvrvs24W4lSd0

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "User",
  "password": "password"
}


### SendMessage
POST http://{{host}}/dialog/LadyGaga/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Sup"
}

### ListDialogs
GET http://{{host}}/dialog/list
Content-Type: application/json
Authorization: Bearer {{token}}

### ListMessages
GET http://{{host}}/dialog/Admin/list
Content-Type: application/json
Authorization: Bearer {{token}}