@host=localhost:8080
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJMYWR5R2FnYSIsImdpdmVuX25hbWUiOiJMYWR5IiwiZmFtaWx5X25hbWUiOiJHYWdhIiwianRpIjoiMDU4OGJlZjYtMjg1Mi00ZmJiLWFlNjctYzZhYjZhN2JmOWQ3IiwiZXhwIjoyMDQxNjQ0NDg0LCJpc3MiOiJIaWdobG9hZFNvY2lhbCIsImF1ZCI6IkhpZ2hsb2FkU29jaWFsIn0.tSDnI7hU4xDTRm-oJG9ygytjK8XlixYmKXNfgmIpLLU

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "LadyGaga",
  "password": "password"
}


### SendMessage
POST http://{{host}}/dialog/User/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Sup User"
}

### ListDialogs
GET http://{{host}}/dialog/list
Content-Type: application/json
Authorization: Bearer {{token}}

### ListMessages
GET http://{{host}}/dialog/User/list
Content-Type: application/json
Authorization: Bearer {{token}}