@host=localhost:80
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJFbGVjdGlvbkxvdzQwNTQiLCJnaXZlbl9uYW1lIjoiTGVhaCIsImZhbWlseV9uYW1lIjoiU3RvbmUiLCJqdGkiOiI1OTRlNzkyNS05ZmIwLTRiNWItODNlZS01MGJmZmEwZWEyNmUiLCJleHAiOjIwNDE1NDg2NjUsImlzcyI6IkhpZ2hsb2FkU29jaWFsIiwiYXVkIjoiSGlnaGxvYWRTb2NpYWwifQ.ZNelR4ziCAsGo9mo1vtz146a0Iu1nmDkuU6qgONDMt4

### Login
POST http://{{host}}/login
Content-Type: application/json

{
  "id": "ElectionLow4054",
  "password": "password"
}

### ListDialogs
GET http://{{host}}/dialog/list
Content-Type: application/json
Authorization: Bearer {{token}}

### ListMessages
GET http://{{host}}/dialog/ElectionLow4054/list
Content-Type: application/json
Authorization: Bearer {{token}}


### SendMessage
POST http://{{host}}/dialog/ElectionLow4054/send
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "text": "Sup"
}